[book]
title = "Kafka Certification Study Guide"
authors = ["Aymen Ben Hmida"]
language = "en"
src = "."

[output.html]
additional-css = ["theme/exam.css"]
additional-js = ["exam.js", "src/dashboard.js", "mermaid.min.js", "mermaid-init.js"]

[preprocessor.mermaid]
command = "mdbook-mermaid"   
